apiVersion: v1
kind: ConfigMap
metadata:
  name: saas-config
  namespace: saas-workspace
data:
  NODE_ENV: production
  PORT: "3000"
  DB_HOST: aws-0-your-region.pooler.supabase.com
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_SSL: "true"
  DB_SYNCHRONIZE: "false"
  REDIS_HOST: your-redis-host.db.redis.io
  REDIS_PORT: "16396"
  REDIS_USERNAME: default
  REDIS_TLS: "false"
  CACHE_STORE: redis
  FRONTEND_URL: http://workspace.local
  JWT_ACCESS_EXPIRES_IN: "15m"
  JWT_REFRESH_EXPIRES_IN: "7d"
  PAYMENT_PROVIDER: mock
  RLS_AUTO_APPLY: "false"
  OTEL_ENABLED: "false"
