apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: saas-workspace
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/peshkash17/multitanant-saas/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: saas-workspace
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
