apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.postgresql.auth.username | quote }}
  DB_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
